<br>

<section>
 <div class="col-lg-13">
 <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/info-emprendimiento.png">
   </div>
</section>


   <section class="page-section portfolio" id="portfolio">
     <div class="container">

      <!-- Portfolio Section Heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"> Emprendedores</h2>

      <!-- Icon Divider -->
      <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon">
      <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
       </div>
       <div class="divider-custom-line"></div>
       </div>
               <p class="text-justify"> <b> Para los emprendedores el software es como una herramienta, así que deben encontrar soluciones específicas para cada una de sus necesidades. En <b>Inner<span style="color:#4BB9DC;">Technology </span></b> le impulsamos a usar software libre en su emprendimiento, ofreciéndole una variedad de herramientas que le ayuden a cumplir sus objetivos, acompañado de un soporte económico y de calidad, de esta manera contribuyendo a su crecimiento como emprendedor.</b></p>
       </div>
        <br>
        <div>&nbsp;</div>


      <!-- Portfolio Grid Items -->
      <div class="row">

        <!-- Portfolio Item 1 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/crm.png">
          </div>
        </div>



        <!-- Portfolio Item 3 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal3">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/Nextcloud.png">
          </div>
        </div>




        <!-- Portfolio Item 6 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal6">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/cocorico.gif" alt="">
          </div>
        </div>

        <!-- Portfolio Item 4 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal4">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/web.png">
          </div>
        </div>

        <!-- Portfolio Item 5 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal5">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/prestashop.png" alt="hey">
          </div>
        </div>
        <!-- Portfolio Item 2 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal2">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/nuevoscript.png">
          </div>
        </div>


      </div>
      <!-- /.row -->

    </div>
  </section>

  <!-- Portfolio Modals -->

  <!-- Portfolio Modal 1 -->
  <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">EspoCRM</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                  <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/portfolio/espo.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"><b>EspoCRM</b> es un software Open Source CRM (Customer Relationship Management) que le permite ver, ingresar y evaluar todas las relaciones de su empresa, independientemente del tipo sean personas, empresas u oportunidades, todo en una interfaz fácil e intuitiva, su objetivo principal es captar y gestionar la relación con cada cliente, es ideal para pymes, emprendedores y autónomos.</p>
                <p><b>Usuario:</b> admin</p>
                <p><b>Contraseña:</b> admin</p>
                <br><br>
                    <button class="btn btn-primary" href="https://demo.innertechnology.co/espoCRM/"><i class="fa fa-bolt"></i> Ver demo</button>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 2 -->
  <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-labelledby="portfolioModal2Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">FacturaScripts para contadores</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                  <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/portfolio/movil.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"><b>FacturaScripts</b> es un software de contabilidad y facturación, multiempresa el cual le permite gestionar pedidos, facturas, factura electrónica, recibos, contabilidad, contactos, tienda online y muchas más cosas de sus clientes, tiene todo lo que necesita un software contable y administrativo. Ya sea un autónomo o contador, tenga 1 producto a 1 millón, haga 10 facturas o 10 millones de facturas, <b>FacturaScripts</b> no tiene límites artificiales de uso, acceda a su facturación y contabilidad desde cualquier sitio, a cualquier hora y con cualquier PC, tablet o smartphone.</p>
                <p><b>Usuario:</b> admin</p>
                <p><b>Contraseña:</b> admin</p>
                <br><br>
                    <button class="btn btn-primary" href="https://demo.innertechnology.co/fs/"><i class="fa fa-bolt"></i> Ver demo</button>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 3 -->
  <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-labelledby="portfolioModal3Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Nextcloud</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                  <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/portfolio/nextcloud2.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b>Nextcloud</b></<b> permite el intercambio seguro de archivos entre empleados, clientes y socios y hace que sus datos estén disponibles en todos los dispositivos, Es una alternativa a Dropbox en el alojamiento de archivos, también es una alternativa a Skype cuenta con un servicio de mensajeria y reuniones, visualización de pantallas, chats en grupo. <b>NextcloudTalk</b> para una mejor comunicación con sus clientes, cuenta con una excelente seguridad de datos implementando cifrado de carpetas y archivos, es ideal para emprendedores o autónomos que buscan control de sus datos. A los notarios, bufetes de abogados y asesores fiscales se les confía el conocimiento más confidencial de sus clientes. Romper esa confianza, por ejemplo debido a una fuga de datos, es un error que termina la carrera.

                <b>Nextcloud</b> le permite concentrarse en su trabajo, cuidando que sus datos permanezcan privados y completamente bajo su control.</p>
                <p><b>Usuario:</b> admin</p>
                <p><b>Contraseña:</b> admin</p>
                <br><br>
                    <button class="btn btn-primary" href="https://demo.innertechnology.co/fs/"><i class="fa fa-bolt"></i> Ver demo</button>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 4 -->
  <div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-labelledby="portfolioModal4Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Desarrollo de sitios web</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                      <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/portfolio/desarrollo.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> Hoy en dia es de vital importancia tener su propio <b>sitio web</b> para darle credibilidad y respaldo a sus ideas o negocios generando confianza ante los clientes y socios, siendo visible las 24 horas al dia. <b>Inner<span style="color:#4BB9DC;">Technology</span></b> realiza el desarrollo y diseño de su <b>sitio web</b> profesional, personalizable y responsive, así empezando sus primeros pasos en la web. </p>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 5 -->
  <div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-labelledby="portfolioModal5Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">prestashop</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                      <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/portfolio/presta.jpg">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b>PrestaShop</b> es una plataforma eCommerce completa, innovadora y eficaz que te permitirá crear tu tienda online y desarrollar tu negocio en internet, es un gestor de contenidos libre y de código abierto, orientado principalmente a la creación de tiendas en línea de comercio electrónico es ideal para emprendedores que desean empezar a vender su catálogo de productos en la web. <b>Inner<span style="color:#4BB9DC;">Technology</span></b> realiza entrega de llave en mano e incluye diseño, gestión de proyectos, integración, desarrollos técnicos, control de calidad, optimización SEO, inicio de producción, hosting, mantenimiento escalable y actualizaciones.</p>
                <button class="btn btn-primary" href="http://demo.prestashop.com/?_ga=2.189773102.483458570.1567373612-542935955.1567373612#/en/front"><i class="fa fa-bolt"></i> Ver demo</button>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 6 -->
  <div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-labelledby="portfolioModal6Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">cocorico</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                     <i style="color:#4BB9DC"; class="fas fa-street-view"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/portfolio/coco.jpg" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b> Cocorico</b> está específicamente diseñado para vender servicios en línea es el caso contrario de <b>PrestaShop</b> que en vez de vender productos <b>Cocorico</b> vende servicios, mercado conocido como Marketplaces. Los mercados se pueden segmentar por tipología de clientes: C2C, B2B y B2C. <b>Inner<span style="color:#4BB9DC;">Technology</span></b> realiza mercados de servicios personalizados, entrega llave en mano e incluye diseño, gestión de proyectos, diseño, integración, desarrollos técnicos, control de calidad, optimización SEO, inicio de producción, hosting, mantenimiento escalable y actualizaciones.</p>
                <button class="btn btn-primary" href="http://demo.prestashop.com/?_ga=2.189773102.483458570.1567373612-542935955.1567373612#/en/front"><i class="fa fa-bolt"></i> Ver demo</button>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>

