<br>
  <section>
      <div class="col-lg-13">
      <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/portfolio/info-sistemas-operativos.png">
        </div>
    </section>

  <section class="page-section portfolio" id="portfolio">
    <div class="container">

      <!-- Portfolio Section Heading -->
      <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0"> Sistema Operativo GNU/LINUX </h2>
      <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon">
        <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
        </div>
        <div class="divider-custom-line"></div>
      </div>
      <p class="text-justify"> <b>Es la base de un sistema operativo libre multiusuario, multiplataforma y multitarea, actualmente cuenta con más de 100 distribuciones diferentes respaldadas por comunidades de todo el mundo. En <b>Inner<span style="color:#4BB9DC;">Technology </span></b>le implementamos el sistema operativo que más se acomode a sus necesidades y preferencias, le ofrecemos soporte en diferentes distribuciones, labor que es facilitada a nuestro grupo de expertos IT en sistemas operativos.</b></p>
    </div>
    <div>&nbsp;</div>


      <!-- Portfolio Grid Items -->

      <div> &nbsp;</div>
      <div>&nbsp;</div>

      <div class="row">

        <!-- Portfolio Item 1 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal1">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/os/deppin.png">
          </div>
        </div>

        <!-- Portfolio Item 2 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal2">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/os/debian.png" alt="">
          </div>
        </div>

        <!-- Portfolio Item 3 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal3">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/os/ubuntu.png" alt="">
          </div>
        </div>

        <!-- Portfolio Item 4 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal4">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/os/Zorin.png" alt="">
          </div>
        </div>

        <!-- Portfolio Item 5 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal5">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/os/kd.png" alt="">
          </div>
        </div>

        <!-- Portfolio Item 6 -->
        <div class="col-md-6 col-lg-4">
          <div class="portfolio-item mx-auto" data-toggle="modal" data-target="#portfolioModal6">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
              <div class="portfolio-item-caption-content text-center text-white">
                <i class="fas fa-plus fa-3x"></i>
              </div>
            </div>
            <img class="img-fluid" src="<?php echo PUBLIC_PATH ?>img/os/mx.jpg" alt="">
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>
  </section>

  <!-- Portfolio Modals -->

  <!-- Portfolio Modal 1 -->
  <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-labelledby="portfolioModal1Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Deppin Os</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                    <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>

                <!-- Portfolio Modal - Image deepin -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/os/deppin.png" alt="">
                <!-- Portfolio Modal - Text -->
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b>Deepin</b> (anteriormente <b>Deepin</b>, Linux Deepin, Hiweed GNU/Linux) es una distribución basada en Debian GNU/Linux con miras a proveer un sistema operativo elegante, amigable con el usuario a la par de ser confiable. No sólo incluye lo mejor que el mundo del código abierto tiene para ofrecer, sino que también ha creado su propio ambiente de escritorio llamado Ambiente de Escritorio <b>Deepin</b> (DDE por sus siglas en inglés) el cual está basado en tecnologías Qt 5. <b>Deepin</b> enfoca mucho de su atención en un diseño intuitivo. Sus aplicaciones creadas en casa como el Centro de Software <b>Deepin</b>, DMusic y DPlayer están hechas a la medida para el usuario promedio. Siendo fácil de instalar y usar, <b></b> puede ser una buena alternativa a Windows para uso en oficina y casa.</p>
                <br><br>
                    <button class="btn btn-primary" href="https://www.deepin.org/es/"><i class="fa fa-star"></i> Visitar Sitio oficial </button>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 2 -->
  <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-labelledby="portfolioModal2Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Debian Os</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                    <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/os/debian.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5">El Proyecto <b>Debian</b> es una asociación de individuos que han hecho un frente común para crear un sistema operativo libre. Este sistema operativo es llamado <b>Debian</b>. Los sistemas <b>Debian</b> actualmente usan el kernel Línux. Línux es una pieza de software completamente libre iniciada por Linus Torvalds y apoyada por miles de programadores en el mundo. Por supuesto, lo que la gente quiere es software de aplicación: Programas que les ayuden a lograr lo que ellos quieran hacer, esto es, desde editar documentos para manejar un negocio hasta jugar juegos o escribir más software. <b>Debian</b> viene con más de 50,000 paquetes (programas precompilados empaquetados en un formato agradable para una fácil instalación en tu máquina) y todo ello sin costo.</p>
                <br><br>
                    <a <button class="btn btn-primary" href="https://www.debian.org/"><i class="fa fa-star"></i> Visitar Sitio oficial </button></a>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 3 -->
  <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-labelledby="portfolioModal3Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Ubuntu Os</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                  <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/os/ubuntu.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b>Ubuntu</b> es un completo sistema operativo Línux de escritorio, disponible gratuitamente con soporte tanto de la comunidad como profesional. La comunidad <b>Ubuntu</b> está construida sobre las ideas consagradas en el manifiesto de <b>Ubuntu</b>: Que el software debe estar disponible libre de cargos, que las herramientas informáticas deben ser usables por gente en su propia lengua y a pesar de cualquier discapacidad, así como el que la gente debe poseer la libertad de personalizar y modificar sus programas en cualesquier forma que les parezca. <b>Ubuntu</b> es una antigua palabra africana que significa "humanidad para los otros". La distribución <b>Ubuntu</b> trae el espíritu de <b>Ubuntu</b> al mundo del software. </p>
                <br><br>
                    <a <button class="btn btn-primary" href="https://ubuntu.com/"><i class="fa fa-star"></i> Visitar Sitio oficial </button></a>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 4 -->
  <div class="portfolio-modal modal fade" id="portfolioModal4" tabindex="-1" role="dialog" aria-labelledby="portfolioModal4Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Zorin os</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                  <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/os/Zorin.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"><b>Zorin OS</b> es una distribución de Línux basada en Ubuntu diseñada especialmente para el recién llegado a Línux. Tiene una inferface de usuario gráfica semejante a la de Windows y muchos programas similares a los encontrados en él. <b>Zorin OS</b> también viene con una aplicación que deja a los usuarios ejecutar muchos programas de Windows. La meta final de la distribución es proveer una alternativa Línux a Windows y dejar a los usuarios de Windows gozar de todas las características de Línux sin complicaciones. </p>
                <br><br>
                    <a <button class="btn btn-primary" href="https://zorinos.com/"><i class="fa fa-star"></i> Visitar Sitio oficial </button></a>
         <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 5 -->
  <div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-labelledby="portfolioModal5Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Kd Neón Os</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                     <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/os/kd.png" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b> KDE neon</b> es un conjunto de repositorios para las ediciones LTS de Ubuntu con la &uacute;ltima versi&oacute;n del escritorio KDE y aplicaciones de 64 bits.​ Es también el nombre dado a una distribución Linux basada en Ubuntu
                    LTS que utiliza dichos repositorios. Su objetivo es proporcionar a los usuarios software Qt y KDE actualizado r&aacute;pidamente, al tiempo que actualiza el resto de los componentes de los repositorios de Ubuntu al ritmo normal.
                    Viene en ediciones de usuario y desarrollador.</p>
                    <br><br>
                    <a <button class="btn btn-primary" href="https://neon.kde.org/"><i class="fa fa-star"></i> Visitar Sitio oficial </button></a>
                <button class="btn btn-primary" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Portfolio Modal 6 -->
  <div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-labelledby="portfolioModal6Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>
        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0">Mx Linux Os</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                    <i style="color:#4BB9DC;" class="fas fa-laptop"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                <!-- Portfolio Modal - Image -->
                <img class="img-fluid rounded mb-5" src="<?php echo PUBLIC_PATH ?>img/os/mx.jpg" alt="">
                <!-- Portfolio Modal - Text -->
                <p class="text-justify" class="mb-5"> <b> MX Linux </b>, distribución de Línux orientada a escritorios, basada en la rama estable de Debian, es un proyecto cooperativo entre las comunidades de antiX y el antiguo MEPIS. Usando Xfce como el escritorio por defecto, es un sistema operativo de medio peso diseñado para combinar un escritorio elegante y eficiente con una configuración simple, alta estabilidad, desempeño sólido y un espacio de tamaño medio. </p>
                <br><br>
                    <a <button class="btn btn-primary" href="https://mxlinux.org/"><i class="fa fa-star"></i> Visitar Sitio oficial </button></a>
                <button class="btn btn-primary" href="#" data-dismiss="modal">
                  <i class="fas fa-times fa-fw"></i>
                  Salir
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
