
<section id="main-slider">
         <div class="owl-carousel">
            <div class="item">
            <img  src="<?php echo PUBLIC_PATH ?>img/slider/loro-tecno.png" style="max-width:100%;height:auto;">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="carousel-content text-center">


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item">
            <img  src="<?php echo PUBLIC_PATH ?>img/slider/loro-tecno.png" style="max-width:100%;height:auto;">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="carousel-content text-center">


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item">
            <img  src="<?php echo PUBLIC_PATH ?>img/slider/loro-tecno.png" style="max-width:100%;height:auto;">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="carousel-content text-center">


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

         </div><!--/.owl-carousel-->
    </section>
