        <!-- Footer -->
        <footer class="footer text-center">
            <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4"><span style="color:#4BB9DC;"><span style=" text-transform:capitalize;">Teléfono</h4>
                <p class="lead mb-0"> <b>+57 3007335164</b>
                    <a href="https://wa.me/573007335164" >
                    <i class="fab fa-fw fa-whatsapp"></i> </p> </a>
                    <br>
                    <p><b><span style="color:#4BB9DC;">Comercial@innertechnology.com.co</b></p>
                </div>


                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                <h4 class="text-uppercase mb-4"> <span style="color:#4BB9DC;"><span style="text-transform:capitalize;">Redes Sociales</h4>

                <a class="btn btn-outline-light btn-social mx-1" href="https://instagram.com/innertechnology_colombia?utm_source=ig_profile_share&igshid=1b3bvg50ydbe0">
                    <i class="fab fa-fw fa-instagram"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://twitter.com/INNERTECHNOLOG1?s=08">
                    <i class="fab fa-fw fa-twitter"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://co.linkedin.com/company/innertechnology?trk=public_profile_topcard_current_company">
                    <i class="fab fa-fw fa-linkedin-in"></i>
                </a>
                <a class="btn btn-outline-light btn-social mx-1" href="https://github.com/">
                    <i class="fab fa-fw fa-github"></i>
                </a>
                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                <span class="text-uppercase mb-4"><b><span style="color:#fff; text-transform:capitalize;">"El utilizar software libre tiene un costo muy alto... Conocimiento!" </b></span>
                <p> <span style="color:#4BB9DC;"><b>Jesús Daniel Mayo Vidal</b></p>
                </div>

            </div>
            </div>
        </footer>

        <!-- Copyright Section -->
        <section class="copyright py-4 text-center text-white">
            <div class="container">
            <p class="text-center">
                <b>&copy; 2019</b> <b>Inner<span style="color:#4BB9DC;">Technology</span></b> <b>Mejoramos e innovamos su plataforma TIC </b>
            </p>
            </div>
        </section>
