<header>  
     <div class="container">

         <!-- Navigation -->
          <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
               <div class="container">
                    <a href="<?php echo PUBLIC_PATH ?>" style="text-decoration: none;"> <span style="color:#fff; text-transform:capitalize;"><B>Inner</B><span style="color:#4BB9DC;"><B>Technology</B></a>
                    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <b>Menú</b>
                    <i class="fas fa-bars"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">

                         <li class="nav-item mx-0 mx-lg-1">
                              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo PUBLIC_PATH ?>"><span style="color:#fff; text-transform:capitalize;"><b>Inicio</b></a>
                         </li>

                         <li class="nav-item mx-0 mx-lg-1">
                              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo PUBLIC_PATH ?>#portafolio"><span style="color:#fff; text-transform:capitalize;"><b>Portafolio</b></a>
                         </li>



                         <li class="nav-item mx-0 mx-lg-1">
                              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="<?php echo PUBLIC_PATH ?>#contact-area"><span style="color:#fff; text-transform:capitalize;"><b>Contactenos</b></a>
                         </li>
                    </ul>
                    </div>
               </div>
          </nav>

          <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->

                    <!-- logo -->
                    <div class="navbar-brand">
                        <a class="smooth-scroll" data-section="#home" href="#home" >
                            <img src="img/logo.png" alt="">
                            <!-- <img src="img/it.png" alt="">-->
                        </a>
                    </div>
                    <!-- /logo -->
           </div>
</header>