

    <!-- Copyright Section -->


    <script src="javascript/jquery/jquery.js"></script>
    <script src="javascript/jquery/bootstrap.min.js"></script>
    <script src="javascript/jquery/owl.carousel.min.js"></script>
    <script src="javascript/jquery/mousescroll.js"></script>
    <script src="javascript/jquery/jquery.prettyPhoto.js"></script>
    <script src="javascript/jquery/jquery.isotope.min.js"></script>
    <script src="javascript/jquery/jquery.inview.min.js"></script>
    <script src="javascript/jquery/wow.min.js"></script>
    <script src="javascript/jquery/main.js"></script>
