    <header id="top-header" class="navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                <a <span style="color:#fff; text-transform:capitalize;"><B> <span style="font-weight: bold;">Inner</B></span><span style="color:#4BB9DC;"><B>Technology</B></a>
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->

                    <!-- logo -->
                    <div class="navbar-brand">
                        <a class="smooth-scroll" data-section="#home" href="#home" >
                            <h1 style="color:#fff; text-transform:capitalize;"><B>Inner</B><span style="color:#4BB9DC;"><B>Technology</B></p>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>
                </div>

                <!-- main nav -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div class="main-menu">
                        <ul id="nav" class="nav navbar-nav">
                            <li class="scroll"><a href="#home" data-section="#home"><b>Inicio</b></a></li>
                            <li class="scroll"><a href="#about" data-section="#about"><b>Nosotros</b></a></li>
                            <li class="scroll"><a href="#services" data-section="#services"><b>Servicios</b></a></li>
                            <li class="scroll"><a href="#portfolio" data-section="#portfolio"><b>Portafolio</b></a></li>
                            <li class="scroll"><a href="#contact-area" data-section="#contact-area"><b>Contáctenos</b></a></li>
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            </div>
    </header>
