<section id="main-slider">
         <div class="owl-carousel">
            <div class="item img_fondo">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="carousel-content text-center">
                                    <h2 style="color: var(--ColorSecond);">MEJORAMOS E INNOVAMOS SU PLATAFORMA TIC</h2>
                                    <p><b>Somos su aliado número uno en el proceso de migración e implementación de software libre</b></p>
                                    <p><b>apoyamos al crecimiento empresarial mediante mejoras en los procesos administrativos</b></p>
                                    <a class="btn btn-primary btn-lg prueba" href="#about">Leer más</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item img_fondo">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="carousel-content text-center">
                                    <h2 style="color: var(--ColorSecond);">¿Por qué elegirnos?</h2>
                                    <p> <b> Somos una alternativa innovadora, con una visión amplia que nos ayuda a encontrar <b style="color: var(--ColorSecond);">SOLUCIONES PRECISAS Y EFICACES</b></b></p>
                                    <p><b>pocas empresas a nivel mundial ofrecen servicios en software libre como InnerTechnology</b></p>
                                    <a class="btn btn-primary btn-lg" href="#services">Leer más</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

            <div class="item img_fondo">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="carousel-content text-center">
                                    <h2 style="color: var(--ColorSecond);">¿Diferencia entre el open source y el software libre?</h2>
                                    <p><b>
                                        La principal diferencia entre el software libre y el open source radica en los derechos de autor con el Copyright representado por el open source y el Copyleft representado por el software libre,
                                        sin embargo comparten mucho en común como es el hecho de que ambos tienen el código abierto al publico, lo importante que se debe destacar es que ambos son elegibles para implementar en cualquier
                                        proyecto respetando su licencias. </b>
                                    </p>
                                    <a class="btn btn-primary btn-lg" href="#portfolio">Leer más</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--/.item-->

         </div><!--/.owl-carousel-->
    </section>
