    <div id="home"></div>

    <!-- slider -->
    <?php View::partial('innert/slider') ?>
    <!--/#main-slider-->
    <!-- portafolio categorias -->
    <br>

    <section id="portfolio" class="cards-section text-center">
            <div class="container">
                <h2 class="title">PORTAFOLIO</h2>
                <div class="intro">
                    <p><b>En Inner<span style="color:#4BB9DC;">Technology</span></b> <span style="font-weight: bold;"> enfocamos nuestro trabajo en diferentes categorias, con el fin de entregar a nuestros clientes soluciones precisas y eficaces que llenen sus expectativas.</span></p>

                </div><!--//intro-->
                <div id="cards-wrapper" class="cards-wrapper row"></div>
                    <div class="item item-blue col-lg-3 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <i class="icon fa fa-building"></i>
                            </div><!--//icon-holder-->
                            <h3 class="title">Pymes</h3>
                            <p class="intro"><b>Software libre para empresas del sector pymes</b></p>
                            <a class="link" href="https://innertechnology.com.co/nva/portafolio/pymes"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-blue item-2 col-lg-3 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                            <i class="icon fa fa-street-view"></i>
                                <span aria-hidden="true" class="icon icon_puzzle_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Emprendedores</h3>
                            <p class="intro"><b>Software libre para emprendedores e independientes</b></p>
                            <a class="link" href="https://innertechnology.com.co/nva/portafolio/emprendedores"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-blue col-lg-3 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                            <i class="icon fa fa-graduation-cap"></i>
                                <span aria-hidden="true" class="icon icon_datareport_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Educación</h3>
                            <p class="intro"><b>Software libre para Universidades y Escuelas</b></p>
                            <a class="link" href="https://innertechnology.com.co/nva/portafolio/educacion"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-blue col-lg-3 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                            <i class="icon fa fa-laptop"></i>
                                <span aria-hidden="true" class="icon icon_lifesaver"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Sistemas Operativos</h3>
                            <p class="intro"><b>Software libre para todos</b></p>
                            <a class="link" href="https://innertechnology.com.co/nva/portafolio/os"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    </div>



    </section>
    <!-- SOBRE NOSOTROS -->
    <section id="about">
        <div class="container">

            <div class="section-header">
                <h2 class="section-title text-center;"> <span style="text-transform:capitalize;"><b>Inner<span style="color: var(--ColorSecond); text-transform:capitalize;">Technology </span></b></h2>
                <p class="text-justify">
                </div>


            <div class="row">
                <div class="col-sm-6 wow fadeInRight" style="word-wrap: break-wrap">
                    <h3 class="column-title">¿Qué hacemos?</h3>

                   <p class="text-justify">  <span  style="font-weight: bold;"> <b>Inner<span style="color: var(--ColorSecond);">Technology </span>ofrece soluciones de software a emprendedores, pymes que necesitan de un software robusto para mejorar sus procesos administrativos.</b>
                    <br>

                    <h3 class="column-title">Visión</h3>

                      <p class="text-justify"> <span style="font-weight: bold;"><b>Inner<span style="color: var(--ColorSecond);">Technology </span>pretende en el 2022 posicionarse en el mercado a nivel nacional e internaciónal, brindando servicios informáticos y
                        soluciones empresariales de manera innovadora con herramientas de codigo abierto y software libre.</b>
                    <br>

                    <h3 class="column-title">Misión</h3>

                      <p class="text-justify">  <span  style="font-weight: bold;"><b>Inner<span style="color: var(--ColorSecond);">Technology </span></b>se fundo para hacer parte del crecimiento empresarial de nuestro país, dando a conocer los beneficios y
                        la confiabilidad del software libre, brindando soluciones innovadoras basandonos en la filosofía del software libre y open source.
                </div>



               <!-- slider about -->
                <div class="col-sm-6 wow fadeInLeft">
                    <div id="carousel-testimonial" class="carousel slide text-center" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <!-- logo -->
                            <div class="item active">
                                <img class="img-responsive" src="img/logo_blanco.png" alt="Logo - InnerTechnology">
                            </div>
                             <!-- Linux torvalds -->
                          <div class="item">
                                <p><img class="img-circle img-thumbnail img-rws" src="img/testimonial/Linus.jpg" alt=""></p>
                                <h4>Linus Torvalds</h4>
                                <span style="font-weight: bold;"><small> Creador de Linux - Padre del movimiento de código abierto</small>
                                <p style="text-align: justify; word-wrap: break-word">
                                <span style="font-weight: bold;"> "No le presto mucha atención a lo que se hace con otros sistemas operativos. No compito, sólo me preocupa hacer que Linux se supere a sí mismo, no a los otros"
                               </span>
                         </div>
                             <!-- Jon Maddog -->
                            <div class="item">
                                <p><img class="img-circle img-thumbnail img-rws" src="img/testimonial/maddog.jpg" alt=""></p>
                                <h4>Jon Maddog</h4>
                                <span style="font-weight: bold;"><small>Creador del proyecto Cauã - Presidente de Linux Foundation</small>
                                <p style="text-align: justify; word-wrap: break-word"> <span style="font-weight: bold;"> "Lo opuesto a la libertad es la esclavitud. Cuando eres esclavo no puedes decidir qué hacer, dónde ir, con quién casarte… no eres tu dueño.
                                </span><span style="font-weight: bold;"> Cuando eres un esclavo del software, no eres dueño del software, el dueño es otro: te dicen cuándo actualizar, dónde comprarlo, cuánta gente lo puede usar, cómo usarlo, la libertad del software te permite tener el control"
                                </span>
                            </div>
                             <!-- imagen rws -->
                            <div class="item">
                                <p><img class="img-circle img-thumbnail img-rws" src="img/testimonial/rws.jpg" alt=""></p>
                                <h4>Richard Stallman</h4>
                              <span style="font-weight: bold;">  <small> Creador del proyecto GNU - Fundador de la Free Software Foundation</small>
                                <p style="text-align: justify; word-wrap: break-word">
                                <span style="font-weight: bold;">  "La elección fácil era unirme al mundo del software propietario, firmar los acuerdos de no revelar, y prometer que no iría en ayuda de mi amigo hacker. Podría haber hecho dinero de esta manera,
                                    y tal vez me hubiera divertido escribiendo codigo. Pero sabía que al final de mi carrera, al mirar atrás los años la pase construyendo paredes para dividir a la gente, sentiría que usé mi vida
                                    para empeorar el mundo"
                                </span>
                            </div>
                         <!-- Controls -->
                        <div class="btns">
                            <a class="btn btn-primary btn-sm" href="#carousel-testimonial" role="button" data-slide="prev">
                                <span class="fa fa-angle-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="btn btn-primary btn-sm" href="#carousel-testimonial" role="button" data-slide="next">
                                <span class="fa fa-angle-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <!-- end slyder sobre nosotros -->
                </div>
            </div>
        </div>
    </div>

    </section><!--/#about-->

    <!-- SERVICIOS -->
    <section id="services" >
        <div class="container">

            <div class="section-header">
                <h2 class="section-title text-center wow fadeInDown"><b>Nuestros </b><span style="color: var(--ColorSecond);"> <b>Servicios</b></h2>
                <!--<p class="text-center wow fadeInDown">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut <br> et dolore magna aliqua. Ut enim ad minim veniam</p>-->
            </div>

            <div class="row">
                <div class="features">

                    <!-- servicios resumen -->
                    <div class="col-sm-6 col-md-4 col-lg-4 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms">
                        <div class="features-item">
                            <div class="features-icon">
                                <i class="fa fa-stack-overflow"></i>
                            </div>
                            <h3  class="features-title font-alt"> <b>Consultoria</b></h3>
                            <span class="parrafo-justificado">
                                Identificamos los conflictos, dificultades y problemas tanto a nivel informático como tecnol&oacute;gico de su empresa o instituci&oacute;n para
                                ofrecerle una soluci&oacute;n robusta basada en software libre. <br>
                                <a href="#consultoria">Leer m&aacute;s</a>
                            </span>
                        </div>
                    </div>

                    <!-- implementacion resumen -->
                    <div class="col-sm-6 col-md-4 col-lg-4 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="100ms">
                        <div class="features-item">
                            <div class="features-icon">
                                <i class="fa fa-bolt"></i>
                            </div>
                            <h3 class="features-title font-alt"><b>Implementación</b></h3>
                            Después de la consultaría y la estrategia planteada por parte de nuestro grupo de expertos, se concreta la segunda fase la cual es la implementación
                            de la herramienta de código abierto seleccionada. <br>
                            <a href="#implementacion">Leer m&aacute;s</a>
                        </div>
                    </div>

                    <!-- soporte resumen -->
                    <div class="col-sm-6 col-md-4 col-lg-4 wow fadeInUp" data-wow-duration="300ms" data-wow-delay="200ms">
                        <div class="features-item">
                            <div class="features-icon">
                                <i  class="fa fa-ticket"></i>
                            </div>
                            <h3 class="features-title font-alt"><b>Soporte</b></h3>
                            Ofrecemos a nuestros clientes la ayuda que nesecitan en sus soluciones inform&aacute;ticas, para que solo se preocupe por gestionar o administrar su empresa
                            y sus tareas diarias. <br>
                            <a href="#soporte">Leer m&aacute;s</a>
                        </div>
                    </div>
                </div>
            </div><!--/.row-->
        </div><!--/.container-->
    </section><!--/#services-->
    <!-- END SERVICIOS -->


    <section id="cta2">
        <div class="container">
            <div class="text-center">
                <h2 class="wow fadeInUp" data-wow-duration="300ms" data-wow-delay="0ms">Sobre nuestros <span>servicios</span></h2>
            </div>
            <hr>
            <br>

            <div id="consultoria"></div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-4" style="margin-top: 20px;">
                        <img src="img/portada1.jpg" class="img-thumbnail" alt="Servicio de consultoria">
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <h3>Consultoria</h3>
                        <p class="parrafo-justificado">
                        <span style="font-weight: bold;"> Realizamos un estudio y análisis a su infraestructura IT, donde identificamos falencias y problemáticas de sus sistemas ofreciendoles soluciones con productos open source y software libre.
                            Nuestro primer paso en la consultoría es visitar su infraestructura IT donde nuestro grupo de expertos implementan un laboratorio open source para hallar las dificultades y a su vez proponiendo las soluciones que se requieran para mejorar e innovar su plataforma TIC.
                            Ejemplo claro de lo dicho anteriormente, es común que nuestros clientes desean ahorrar sus recursos económicos implementando software libre y herramientas de código abierto, intervenimos guiando a las mejores soluciones para alcanzar dicho objetivo donde la solución sea tanto económica como funcional para su negocio.
                            Tenemos los argumentos necesarios para demostrarles porque es mucho mejor empezar a migrar a tecnologías abiertas y libres. </span>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-md-offset-3"><hr></div>

            <div id="implementacion"></div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-4" style="margin-top: 20px;">
                        <img src="img/implementacion.jpg" class="img-thumbnail" alt="Servicio de implementacion">
                    </div>
                    <div class="col-sm-12 col-md-8"  style="margin-top: 45px;">
                        <h3>Implementaci&oacute;n</h3>
                        <p class="parrafo-justificado">
                        <span style="font-weight: bold;"> Despu&eacute;s de evaluar los procesos administrativos de nuestros clientes y determinar cual es la mejor opci&oacute;n tecnol&oacute;gica, implementamos el sistema y capacitamos
                            a su personal para utilizar las herramientas que harán que sus tareas sean m&aacute;s f&aacute;ciles.

                            Nuestras soluciones se ajustan a las necesidades y al flujo de trabajo (workflow) de su empresa, esa es una de las grandes ventajas del software
                            libre y/o open source, el servicio puede alojarse en nuestros servidores o en los suyos como usted lo considere pertinente.</span>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-md-offset-3"><hr></div>

            <div id="soporte"></div>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-4" style="margin-top: 20px;">
                        <img src="img/soporte.jpg" class="img-thumbnail" alt="Servicio de implementacion">
                    </div>
                    <div class="col-sm-12 col-md-8"  style="margin-top: 45px;">
                        <h3> Soporte</h3>
                        <p class="parrafo-justificado">
                        <span style="font-weight: bold;">Nuestros clientes solo piensan en su negocio, porqu&eacute; nosotros apoyamos sus innovaciones mejorando
                            las soluciones implementadas para satisfacer las necesidades de su negocio, generandole vída utíl al software.

                            Para esta tarea tan importante contamos con un equipo de trabajo profesional, capacitado para ofrecer la mejor experiencia al cliente brindandole la soluci&oacute;n m&aacute;s precisa y eficaz
                            seg&uacute;n sus necesidades; somos su aliado número uno en software libre.</span>
                        </p>
                    </div>
                </div>
            </div>

        </div>

    </section>
    <footer id="footer">
        <p class="text-center">
            <span style="color:#4BB9DC;"><span style="font-size:28px;"><b>Redes Sociales</b></span>

                <ul class="social-icons text-center">

                        <li><a href="#"><i class="fa fa-twitter fa-2x"></i></a></li>
                        <li><a href="#"><i class="fa fa-github fa-2x"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram fa-2x"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube fa-2x"></i></a></li>
                        <li><a href="https://wa.me/573007335164"><i class="fa fa-whatsapp fa-2x"></i></a></li>
                    </ul>
                     <br>
                    <ul class="social-icons text-center">
                    <a><span  style="color:#4BB9DC;"><span style="font-size:18px;"><b>Comercial@innertechnology.com.co</b></a>
                </ul>

            </footer>

            <section id="contact-area" class="copyright py-4 text-center text-white">
            <div class="container">
            <p class="text-center">
                <b>&copy;2019</b> <b>Inner<span style="color:#4BB9DC;">Technology</span></b> <b>Mejoramos e innovamos su plataforma TIC </b>
            </p>
            </div>
        </section>


